/*
 * ultrasonic.c
 *
 *  Created on: Oct 14, 2021
 *      Author: youssef
 */

#include "ultrasonic.h"
#include "gpio.h"
#include"std_types.h"
#include"icu.h"
#include <util/delay.h>
uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;




/*
 * Description
 Initialize the ICU driver as required.
 Setup the ICU call back function.
 Setup the direction for the trigger pin as output pin through the GPIO driver.
 Inputs: None
 Return: None
 * */
void Ultrasonic_init(void)
{


	Icu_setCallBack(Ultrasonic_edgeProcessing); // call back function address stored so the ISR call this function every edge

	GPIO_setupPinDirection(Trigger_port,Trigger_pin, PIN_OUTPUT); // make the trigger pin output

	}
/*Description
 Send the Trigger pulse to the ultrasonic.
 Inputs: None
 Return: None*/
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(Trigger_port,Trigger_pin , LOGIC_HIGH);

	_delay_us(1);

	GPIO_writePin(Trigger_port,Trigger_pin , LOGIC_LOW);

	}
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance =0;

	 Ultrasonic_Trigger();

	 distance = ( g_timeHigh)/(57.5);

	return distance ;
	}
/*
 * This is the call back function called by the ICU driver.
  This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 *
 * */
void Ultrasonic_edgeProcessing(void)
{

	g_edgeCount++;

	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge after we detected the rising edge in the  (Ultrasonic_init) function */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value of the first pulse and this time equals the time take the sound to travel to object and come back */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge of the next wave  */ /*note the init function detect the rising edge only one time so i need to make the ICU detect
		 * rising edge with every change happens in the environment */
		Icu_setEdgeDetectionType(RISING);
		/* reset the g_edgeCount so we cane count again and use the Ultrasonic_edgeProcessing function to the next pulse */
		g_edgeCount=0;
	}

}


